---
- name: Install build tools
  yum:
    name:
      - devtoolset-10
      - llvm-toolset-10.0
      - llvm-toolset-10.0-git-clang-format
      - llvm-toolset-10.0-clang-tools-extra
    state: latest
    use_backend: yum
  become: yes

- name: Enable devtoolset globally for all users
  # See https://developers.redhat.com/blog/2014/03/19/permanently-enable-a-software-collection/
  copy:
    src: enable-devtoolset.sh
    dest: /etc/profile.d/enable-devtoolset.sh
  become: yes

- name: Enable llvm-toolset globally for all users
  copy:
    src: enable-llvm-toolset.sh
    dest: /etc/profile.d/enable-llvm-toolset.sh
  become: yes
