---
- name: Check for existing Xcode installation
  stat:
    path: /Applications/Xcode.app
  register: xcode_app

- name: Download XCode
  get_url:
    url: "{{ xcode_xip_url }}"
    headers:
      X-JFrog-Art-Api: "{{ansible_deployment_artifactory_key}}"
    dest: ~/Downloads/xcode.xip
    mode: '0440'
  when: xcode_app.stat.isdir is not defined or not xcode_app.stat.isdir

- name: Extract XCode archive
  command: xip -x ~/Downloads/xcode.xip
  args:
    chdir: "/Applications"
    creates: "/Applications/Xcode.app"
  register: extract_xcode_xip

- name: Remove downloaded Xcode archive
  file:
    state: absent
    path: ~/Downloads/xcode.xip
  
- name: Accept Xcode licence
  command: xcodebuild -license accept
  become: true

- name: Get list of installed packages
  command: pkgutil --pkgs
  register: pkgutil_packages

- name: Get list of packages available with Xcode
  find:
    path: /Applications/Xcode.app/Contents/Resources/Packages/
    patterns: '*.pkg'
    recurse: no
  register: packages

- name: Install Xcode packages
  include: install-pkg.yml
  vars:
    package_file: "{{ package }}"
    package_list: "{{ pkgutil_packages.stdout }}"
  with_items: "{{ packages.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: package
