---
- name: Install build tools
  ansible.builtin.dnf:
    name:
      - '@Development tools'
      - llvm-toolset
      - clang
      - clang-tools-extra
      - git-clang-format
      - gcc-toolset-10
      - gcc-toolset-10-runtime
      - gcc-toolset-10-libatomic-devel
    state: present
  become: true

- name: Create a symbolic link devtoolset-10 linking to gcc-toolset-10
  ansible.builtin.file:
    src: /opt/rh/gcc-toolset-10
    dest: /opt/rh/devtoolset-10
    owner: root
    group: root
    state: link
  become: true
