---
- name: Install build tools
  ansible.builtin.dnf:
    name:
      - '@Development tools'
      - llvm-toolset
      - clang
      - clang-tools-extra
      - git-clang-format
      - gcc-toolset-10
      - gcc-toolset-10-runtime
    state: present
  become: true

- name: Create a symbolic link devtoolset-10 linking to gcc-toolset-10
  ansible.builtin.file:
    src: /opt/rh/gcc-toolset-10
    dest: /opt/rh/devtoolset-10
    state: link

- name: Enable devtoolset globally for all users
  # See https://developers.redhat.com/blog/2014/03/19/permanently-enable-a-software-collection/
  ansible.builtin.copy:
    src: enable-devtoolset.sh
    dest: /etc/profile.d/enable-devtoolset.sh
    mode: u=rwx,g=rx,o=rx
  become: true

# - name: Enable llvm-toolset globally for all users
#   ansible.builtin.copy:
#     src: enable-llvm-toolset.sh
#     dest: /etc/profile.d/enable-llvm-toolset.sh
#     mode: u=rwx,g=rx,o=rx
#   become: true
