---
- name: Install visualstudio2026professional (SLOW)
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2026professional
    state: present

- name: Install visualstudio2026-workload-nativedesktop (SLOW)
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2026-workload-nativedesktop
    state: present

- name: Install visualstudio2026-remotetools
  chocolatey.chocolatey.win_chocolatey:
    name: visualstudio2026-remotetools
    state: present
