---
- name: Install Visual Studio Professional (SLOW)
  chocolatey.chocolatey.win_chocolatey:
    name:
      - visualstudio2022professional
      - visualstudio2026professional
    state: present

- name: Install Visual Studio Workload Native Desktop (SLOW)
  chocolatey.chocolatey.win_chocolatey:
    name: 
      - visualstudio2022-workload-nativedesktop
      - visualstudio2026-workload-nativedesktop
    state: present

- name: Install Visual Studio Remotetools
  chocolatey.chocolatey.win_chocolatey:
    name:
      - visualstudio2022-remotetools
      - visualstudio2026-remotetools
    state: present
